// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqy845mkSj6uokTRN2HAr2R3nxWSRglI',
    appId: '1:309592921069:web:f4c79d0e66fc1145900de4',
    messagingSenderId: '309592921069',
    projectId: 'financas-pessoais-8d85b',
    authDomain: 'financas-pessoais-8d85b.firebaseapp.com',
    storageBucket: 'financas-pessoais-8d85b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmA4kVD2G4o2AxjXdInhyslu5FlbrlbTo',
    appId: '1:309592921069:android:71f89e7f0ccda95e900de4',
    messagingSenderId: '309592921069',
    projectId: 'financas-pessoais-8d85b',
    storageBucket: 'financas-pessoais-8d85b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-vsZqHnsDkEQEIPNAc6GP18Kq_ew568',
    appId: '1:309592921069:ios:b8beb01878f96650900de4',
    messagingSenderId: '309592921069',
    projectId: 'financas-pessoais-8d85b',
    storageBucket: 'financas-pessoais-8d85b.firebasestorage.app',
    iosBundleId: 'com.example.financasPessoais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-vsZqHnsDkEQEIPNAc6GP18Kq_ew568',
    appId: '1:309592921069:ios:b8beb01878f96650900de4',
    messagingSenderId: '309592921069',
    projectId: 'financas-pessoais-8d85b',
    storageBucket: 'financas-pessoais-8d85b.firebasestorage.app',
    iosBundleId: 'com.example.financasPessoais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRqy845mkSj6uokTRN2HAr2R3nxWSRglI',
    appId: '1:309592921069:web:0283e3bdb1d9f4f0900de4',
    messagingSenderId: '309592921069',
    projectId: 'financas-pessoais-8d85b',
    authDomain: 'financas-pessoais-8d85b.firebaseapp.com',
    storageBucket: 'financas-pessoais-8d85b.firebasestorage.app',
  );

}